/**
 * アイカツ！アンコール カードデータ
 * 
 * id      : 公式 images/cardlist/card/ の画像ファイル名（拡張子なし）
 * rarity  : N / R / PR / ER
 * series  : "1" = 1弾, "promo" = プロモーション
 * image   : GitHubの images/ フォルダに置くパス
 * 
 * 裏面（_b）は除外しています
 */

const CARDS = [
  // ========================================
  // 1弾（全85枚）
  // ========================================
  { id: "E1-01_PR", name: "E1-01 PR", rarity: "PR", series: "1", image: "images/E1-01_PR.webp" },
  { id: "E1-02_PR", name: "E1-02 PR", rarity: "PR", series: "1", image: "images/E1-02_PR.webp" },
  { id: "E1-03_PR", name: "E1-03 PR", rarity: "PR", series: "1", image: "images/E1-03_PR.webp" },
  { id: "E1-04_PR", name: "E1-04 PR", rarity: "PR", series: "1", image: "images/E1-04_PR.webp" },
  { id: "E1-05_R",  name: "E1-05 R",  rarity: "R",  series: "1", image: "images/E1-05_R.webp" },
  { id: "E1-06_R",  name: "E1-06 R",  rarity: "R",  series: "1", image: "images/E1-06_R.webp" },
  { id: "E1-07_R",  name: "E1-07 R",  rarity: "R",  series: "1", image: "images/E1-07_R.webp" },
  { id: "E1-08_R",  name: "E1-08 R",  rarity: "R",  series: "1", image: "images/E1-08_R.webp" },
  { id: "E1-09_R",  name: "E1-09 R",  rarity: "R",  series: "1", image: "images/E1-09_R.webp" },
  { id: "E1-10_R",  name: "E1-10 R",  rarity: "R",  series: "1", image: "images/E1-10_R.webp" },
  { id: "E1-11_R",  name: "E1-11 R",  rarity: "R",  series: "1", image: "images/E1-11_R.webp" },
  { id: "E1-12_R",  name: "E1-12 R",  rarity: "R",  series: "1", image: "images/E1-12_R.webp" },
  { id: "E1-13_R",  name: "E1-13 R",  rarity: "R",  series: "1", image: "images/E1-13_R.webp" },
  { id: "E1-14_R",  name: "E1-14 R",  rarity: "R",  series: "1", image: "images/E1-14_R.webp" },
  { id: "E1-15_R",  name: "E1-15 R",  rarity: "R",  series: "1", image: "images/E1-15_R.webp" },
  { id: "E1-16_R",  name: "E1-16 R",  rarity: "R",  series: "1", image: "images/E1-16_R.webp" },
  { id: "E1-17_R",  name: "E1-17 R",  rarity: "R",  series: "1", image: "images/E1-17_R.webp" },
  { id: "E1-18_R",  name: "E1-18 R",  rarity: "R",  series: "1", image: "images/E1-18_R.webp" },
  { id: "E1-19_R",  name: "E1-19 R",  rarity: "R",  series: "1", image: "images/E1-19_R.webp" },
  { id: "E1-20_R",  name: "E1-20 R",  rarity: "R",  series: "1", image: "images/E1-20_R.webp" },
  { id: "E1-21_N",  name: "E1-21 N",  rarity: "N",  series: "1", image: "images/E1-21_N.webp" },
  { id: "E1-22_N",  name: "E1-22 N",  rarity: "N",  series: "1", image: "images/E1-22_N.webp" },
  { id: "E1-23_N",  name: "E1-23 N",  rarity: "N",  series: "1", image: "images/E1-23_N.webp" },
  { id: "E1-24_N",  name: "E1-24 N",  rarity: "N",  series: "1", image: "images/E1-24_N.webp" },
  { id: "E1-25_N",  name: "E1-25 N",  rarity: "N",  series: "1", image: "images/E1-25_N.webp" },
  { id: "E1-26_N",  name: "E1-26 N",  rarity: "N",  series: "1", image: "images/E1-26_N.webp" },
  { id: "E1-27_N",  name: "E1-27 N",  rarity: "N",  series: "1", image: "images/E1-27_N.webp" },
  { id: "E1-28_N",  name: "E1-28 N",  rarity: "N",  series: "1", image: "images/E1-28_N.webp" },
  { id: "E1-29_N",  name: "E1-29 N",  rarity: "N",  series: "1", image: "images/E1-29_N.webp" },
  { id: "E1-30_ER", name: "E1-30 ER", rarity: "ER", series: "1", image: "images/E1-30_ER.webp" },
  { id: "E1-31_ER", name: "E1-31 ER", rarity: "ER", series: "1", image: "images/E1-31_ER.webp" },
  { id: "E1-32_ER", name: "E1-32 ER", rarity: "ER", series: "1", image: "images/E1-32_ER.webp" },
  { id: "E1-33_PR", name: "E1-33 PR", rarity: "PR", series: "1", image: "images/E1-33_PR.webp" },
  { id: "E1-34_PR", name: "E1-34 PR", rarity: "PR", series: "1", image: "images/E1-34_PR.webp" },
  { id: "E1-35_PR", name: "E1-35 PR", rarity: "PR", series: "1", image: "images/E1-35_PR.webp" },
  { id: "E1-36_PR", name: "E1-36 PR", rarity: "PR", series: "1", image: "images/E1-36_PR.webp" },
  { id: "E1-37_R",  name: "E1-37 R",  rarity: "R",  series: "1", image: "images/E1-37_R.webp" },
  { id: "E1-38_R",  name: "E1-38 R",  rarity: "R",  series: "1", image: "images/E1-38_R.webp" },
  { id: "E1-39_R",  name: "E1-39 R",  rarity: "R",  series: "1", image: "images/E1-39_R.webp" },
  { id: "E1-40_R",  name: "E1-40 R",  rarity: "R",  series: "1", image: "images/E1-40_R.webp" },
  { id: "E1-41_N",  name: "E1-41 N",  rarity: "N",  series: "1", image: "images/E1-41_N.webp" },
  { id: "E1-42_N",  name: "E1-42 N",  rarity: "N",  series: "1", image: "images/E1-42_N.webp" },
  { id: "E1-43_N",  name: "E1-43 N",  rarity: "N",  series: "1", image: "images/E1-43_N.webp" },
  { id: "E1-44_N",  name: "E1-44 N",  rarity: "N",  series: "1", image: "images/E1-44_N.webp" },
  { id: "E1-45_N",  name: "E1-45 N",  rarity: "N",  series: "1", image: "images/E1-45_N.webp" },
  { id: "E1-46_N",  name: "E1-46 N",  rarity: "N",  series: "1", image: "images/E1-46_N.webp" },
  { id: "E1-47_N",  name: "E1-47 N",  rarity: "N",  series: "1", image: "images/E1-47_N.webp" },
  { id: "E1-48_N",  name: "E1-48 N",  rarity: "N",  series: "1", image: "images/E1-48_N.webp" },
  { id: "E1-49_N",  name: "E1-49 N",  rarity: "N",  series: "1", image: "images/E1-49_N.webp" },
  { id: "E1-50_ER", name: "E1-50 ER", rarity: "ER", series: "1", image: "images/E1-50_ER.webp" },
  { id: "E1-51_PR", name: "E1-51 PR", rarity: "PR", series: "1", image: "images/E1-51_PR.webp" },
  { id: "E1-52_PR", name: "E1-52 PR", rarity: "PR", series: "1", image: "images/E1-52_PR.webp" },
  { id: "E1-53_R",  name: "E1-53 R",  rarity: "R",  series: "1", image: "images/E1-53_R.webp" },
  { id: "E1-54_R",  name: "E1-54 R",  rarity: "R",  series: "1", image: "images/E1-54_R.webp" },
  { id: "E1-55_R",  name: "E1-55 R",  rarity: "R",  series: "1", image: "images/E1-55_R.webp" },
  { id: "E1-56_R",  name: "E1-56 R",  rarity: "R",  series: "1", image: "images/E1-56_R.webp" },
  { id: "E1-57_R",  name: "E1-57 R",  rarity: "R",  series: "1", image: "images/E1-57_R.webp" },
  { id: "E1-58_R",  name: "E1-58 R",  rarity: "R",  series: "1", image: "images/E1-58_R.webp" },
  { id: "E1-59_R",  name: "E1-59 R",  rarity: "R",  series: "1", image: "images/E1-59_R.webp" },
  { id: "E1-60_N",  name: "E1-60 N",  rarity: "N",  series: "1", image: "images/E1-60_N.webp" },
  { id: "E1-61_N",  name: "E1-61 N",  rarity: "N",  series: "1", image: "images/E1-61_N.webp" },
  { id: "E1-62_N",  name: "E1-62 N",  rarity: "N",  series: "1", image: "images/E1-62_N.webp" },
  { id: "E1-63_N",  name: "E1-63 N",  rarity: "N",  series: "1", image: "images/E1-63_N.webp" },
  { id: "E1-64_N",  name: "E1-64 N",  rarity: "N",  series: "1", image: "images/E1-64_N.webp" },
  { id: "E1-65_N",  name: "E1-65 N",  rarity: "N",  series: "1", image: "images/E1-65_N.webp" },
  { id: "E1-66_N",  name: "E1-66 N",  rarity: "N",  series: "1", image: "images/E1-66_N.webp" },
  { id: "E1-67_N",  name: "E1-67 N",  rarity: "N",  series: "1", image: "images/E1-67_N.webp" },
  { id: "E1-68_N",  name: "E1-68 N",  rarity: "N",  series: "1", image: "images/E1-68_N.webp" },
  { id: "E1-69_N",  name: "E1-69 N",  rarity: "N",  series: "1", image: "images/E1-69_N.webp" },
  { id: "E1-70_N",  name: "E1-70 N",  rarity: "N",  series: "1", image: "images/E1-70_N.webp" },
  { id: "E1-71_PR", name: "E1-71 PR", rarity: "PR", series: "1", image: "images/E1-71_PR.webp" },
  { id: "E1-72_PR", name: "E1-72 PR", rarity: "PR", series: "1", image: "images/E1-72_PR.webp" },
  { id: "E1-73_PR", name: "E1-73 PR", rarity: "PR", series: "1", image: "images/E1-73_PR.webp" },
  { id: "E1-74_PR", name: "E1-74 PR", rarity: "PR", series: "1", image: "images/E1-74_PR.webp" },
  { id: "E1-75_PR", name: "E1-75 PR", rarity: "PR", series: "1", image: "images/E1-75_PR.webp" },
  { id: "E1-76_PR", name: "E1-76 PR", rarity: "PR", series: "1", image: "images/E1-76_PR.webp" },
  { id: "E1-77_PR", name: "E1-77 PR", rarity: "PR", series: "1", image: "images/E1-77_PR.webp" },
  { id: "E1-78_PR", name: "E1-78 PR", rarity: "PR", series: "1", image: "images/E1-78_PR.webp" },
  { id: "E1-79_PR", name: "E1-79 PR", rarity: "PR", series: "1", image: "images/E1-79_PR.webp" },
  { id: "E1-80_PR", name: "E1-80 PR", rarity: "PR", series: "1", image: "images/E1-80_PR.webp" },
  { id: "E1-81_PR", name: "E1-81 PR", rarity: "PR", series: "1", image: "images/E1-81_PR.webp" },
  { id: "E1-82_PR", name: "E1-82 PR", rarity: "PR", series: "1", image: "images/E1-82_PR.webp" },
  { id: "E1-83_N",  name: "E1-83 N",  rarity: "N",  series: "1", image: "images/E1-83_N.webp" },
  { id: "E1-84_N",  name: "E1-84 N",  rarity: "N",  series: "1", image: "images/E1-84_N.webp" },
  { id: "E1-85_N",  name: "E1-85 N",  rarity: "N",  series: "1", image: "images/E1-85_N.webp" },

  // ========================================
  // プロモーション（全22枚）
  // ========================================
  { id: "EP-001_N",  name: "EP-001 N",  rarity: "N",  series: "promo", image: "images/EP-001_N.webp" },
  { id: "EP-002_PR", name: "EP-002 PR", rarity: "PR", series: "promo", image: "images/EP-002_PR.webp" },
  { id: "EP-003_N",  name: "EP-003 N",  rarity: "N",  series: "promo", image: "images/EP-003_N.webp" },
  { id: "EP-004_N",  name: "EP-004 N",  rarity: "N",  series: "promo", image: "images/EP-004_N.webp" },
  { id: "EP-005_N",  name: "EP-005 N",  rarity: "N",  series: "promo", image: "images/EP-005_N.webp" },
  { id: "EP-006_N",  name: "EP-006 N",  rarity: "N",  series: "promo", image: "images/EP-006_N.webp" },
  { id: "EP-007_N",  name: "EP-007 N",  rarity: "N",  series: "promo", image: "images/EP-007_N.webp" },
  { id: "EP-008_N",  name: "EP-008 N",  rarity: "N",  series: "promo", image: "images/EP-008_N.webp" },
  { id: "EP-009_N",  name: "EP-009 N",  rarity: "N",  series: "promo", image: "images/EP-009_N.webp" },
  { id: "EP-010_N",  name: "EP-010 N",  rarity: "N",  series: "promo", image: "images/EP-010_N.webp" },
  { id: "EP-011_N",  name: "EP-011 N",  rarity: "N",  series: "promo", image: "images/EP-011_N.webp" },
  { id: "EP-012_N",  name: "EP-012 N",  rarity: "N",  series: "promo", image: "images/EP-012_N.webp" },
  { id: "EP-013_N",  name: "EP-013 N",  rarity: "N",  series: "promo", image: "images/EP-013_N.webp" },
  { id: "EP-014_N",  name: "EP-014 N",  rarity: "N",  series: "promo", image: "images/EP-014_N.webp" },
  { id: "EP-015_N",  name: "EP-015 N",  rarity: "N",  series: "promo", image: "images/EP-015_N.webp" },
  { id: "EP-016_N",  name: "EP-016 N",  rarity: "N",  series: "promo", image: "images/EP-016_N.webp" },
  { id: "EP-017_N",  name: "EP-017 N",  rarity: "N",  series: "promo", image: "images/EP-017_N.webp" },
  { id: "EP-018_N",  name: "EP-018 N",  rarity: "N",  series: "promo", image: "images/EP-018_N.webp" },
  { id: "EP-029_R",  name: "EP-029 R",  rarity: "R",  series: "promo", image: "images/EP-029_R.webp" },
  { id: "EP-030_R",  name: "EP-030 R",  rarity: "R",  series: "promo", image: "images/EP-030_R.webp" },
  { id: "EP-037_N",  name: "EP-037 N",  rarity: "N",  series: "promo", image: "images/EP-037_N.webp" },
  { id: "EP-038_N",  name: "EP-038 N",  rarity: "N",  series: "promo", image: "images/EP-038_N.webp" },
];
